EMOTION_MODEL="app/model/distilbert-base-uncased-go-emotions"
DEPRESSION_MODEL="app/model/distilbert-base-uncased-depress-model"
PASSWORD = "pioneersp"
DB_URL = f"mongodb+srv://pioneersp:{PASSWORD}@cluster0.rrnp1r4.mongodb.net/?retryWrites=true&w=majority"
DB_NAME = "org_details"
CONTRACTION_MAPPING = {
    "ain't": "is not",
    "aren't": "are not",
    "can't": "cannot",
    "can't've": "cannot have",
    "could've": "could have",
    "couldn't": "could not",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't": "had not",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he would",
    "he'll": "he will",
    "he's": "he is",
    "how'd": "how did",
    "how'll": "how will",
    "how's": "how is",
    "i'd": "i would",
    "i'll": "i will",
    "i'm": "i am",
    "i've": "i have",
    "isn't": "is not",
    "it'd": "it would",
    "it'll": "it will",
    "it's": "it is",
    "let's": "let us",
    "ma'am": "madam",
    "mightn't": "might not",
    "mustn't": "must not",
    "needn't": "need not",
    "oughtn't": "ought not",
    "shan't": "shall not",
    "she'd": "she would",
    "she'll": "she will",
    "she's": "she is",
    "should've": "should have",
    "shouldn't": "should not",
    "that's": "that is",
    "there's": "there is",
    "they'd": "they would",
    "they'll": "they will",
    "they're": "they are",
    "they've": "they have",
    "wasn't": "was not",
    "we'd": "we would",
    "we'll": "we will",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    "what'll": "what will",
    "what're": "what are",
    "what's": "what is",
    "what've": "what have",
    "where's": "where is",
    "who'd": "who would",
    "who'll": "who will",
    "who're": "who are",
    "who's": "who is",
    "who've": "who have",
    "won't": "will not",
    "wouldn't": "would not",
    "you'd": "you would",
    "you'll": "you will",
    "you're": "you are",
    "you've": "you have"
}

HAPPY_LABEL = [
    "admiration",
    "amusement",
    "excitement",
    "joy",
    "love",
    "optimism",
    "pride",
    "relief",
    "caring",
    "approval",
    "gratitude",
    "surprise"
]

LABEL_SCORES = {
    "admiration": 8,
    "amusement": 8,
    "anger": 2,
    "annoyance": 3,
    "approval": 7,
    "caring": 9,
    "confusion": 4,
    "curiosity": 6,
    "desire": 7,
    "disappointment": 3,
    "disapproval": 2,
    "disgust": 1,
    "embarrassment": 2,
    "excitement": 8,
    "fear": 1,
    "gratitude": 9,
    "grief": 2,
    "joy": 10,
    "love": 10,
    "nervousness": 2,
    "optimism": 8,
    "pride": 8,
    "realization": 5,
    "relief": 7,
    "remorse": 2,
    "sadness": 1,
    "surprise": 6,
    "neutral": 5 
}

STRESS_LABELS = {
    "admiration": 1,
    "amusement": 2,
    "anger": 9,
    "annoyance": 7,
    "approval": 1,
    "caring": 2,
    "confusion": 6,
    "curiosity": 4,
    "desire": 5,
    "disappointment": 7,
    "disapproval": 8,
    "disgust": 9,
    "embarrassment": 8,
    "excitement": 2,
    "fear": 10,
    "gratitude": 1,
    "grief": 9,
    "joy": 1,
    "love": 1,
    "nervousness": 8,
    "optimism": 2,
    "pride": 1,
    "realization": 5,
    "relief": 3,
    "remorse": 7,
    "sadness": 9,
    "surprise": 5,
    "neutral": 6
}

